services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fpm-ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  sut:
    image: alpine:3.21
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./run_tests.sh:/run_tests.sh:ro
    command: sh /run_tests.sh
