services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
    ports:
      - "8080:8080"
  test:
    image: alpine:3.21
    depends_on:
      - app
    command: sh -c "
      echo '等待应用启动...'
      sleep 15
      echo '安装curl...'
      apk --no-cache add curl
      echo '测试连接...'
      curl -f http://app:8080/php.php && echo 'PHP页面访问成功' || echo 'PHP页面访问失败'
    "
