# Docker Compose 环境变量配置示例
# 展示不同环境变量配置的使用方法

version: '3.8'

# 小型网站配置示例 - 默认配置
services:
  php-nginx-small:
    image: zhoujie218/php-nginx:latest
    container_name: php-nginx-small
    ports:
      - "8080:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=64M
      - OPCACHE_MEMORY=32
      - REDIS_MAXMEMORY=64mb
      - FPM_MAX_CHILDREN=20
    restart: unless-stopped
    profiles:
      - small

# 中型网站配置示例
  php-nginx-medium:
    image: zhoujie218/php-nginx:latest
    container_name: php-nginx-medium
    ports:
      - "8081:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=128M
      - OPCACHE_MEMORY=64
      - REDIS_MAXMEMORY=128mb
      - FPM_MAX_CHILDREN=30
    restart: unless-stopped
    profiles:
      - medium

# 大型网站配置示例
  php-nginx-large:
    image: zhoujie218/php-nginx:latest
    container_name: php-nginx-large
    ports:
      - "8082:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
      - OPCACHE_MEMORY=128
      - REDIS_MAXMEMORY=256mb
      - FPM_MAX_CHILDREN=50
      - FPM_PM_MODE=static
      - NGINX_WORKER_PROCESSES=2
    restart: unless-stopped
    profiles:
      - large

# 自定义配置示例 - 通过环境变量自定义
  php-nginx-custom:
    image: zhoujie218/php-nginx:latest
    container_name: php-nginx-custom
    ports:
      - "8085:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      # 自定义PHP配置
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_POST_MAX_SIZE=32M
      - PHP_UPLOAD_MAX_FILESIZE=16M
      
      # 自定义OPcache配置
      - OPCACHE_MEMORY=128
      - OPCACHE_MAX_ACCELERATED_FILES=8000
      
      # 自定义PHP-FPM配置
      - FPM_PM_MODE=dynamic
      - FPM_MAX_CHILDREN=40
      - FPM_START_SERVERS=8
      - FPM_MIN_SPARE_SERVERS=4
      - FPM_MAX_SPARE_SERVERS=20
      
      # 自定义Nginx配置
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=2048
      - NGINX_GZIP_COMP_LEVEL=6
      
      # 自定义Redis配置
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    restart: unless-stopped
    profiles:
      - custom

# 开发环境配置示例
  php-nginx-dev:
    image: zhoujie218/php-nginx:latest
    container_name: php-nginx-dev
    ports:
      - "8086:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      # 开发环境优化
      - PHP_DISPLAY_ERRORS=On
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_MEMORY_LIMIT=128M
      - OPCACHE_ENABLE=0  # 开发时禁用OPcache
      - FPM_PM_MODE=dynamic
      - FPM_MAX_CHILDREN=10
    restart: unless-stopped
    profiles:
      - dev

# 生产环境配置示例 - 高可用配置
  php-nginx-prod:
    image: zhoujie218/php-nginx:latest
    container_name: php-nginx-prod
    ports:
      - "8087:8080"
    volumes:
      - ./src:/var/www/html
    environment:
      # 生产环境优化
      - RESOURCE_PROFILE=2h4g
      - PHP_DISPLAY_ERRORS=Off
      - PHP_LOG_ERRORS=On
      - FPM_PM_MODE=static
      - OPCACHE_ENABLE=1
      - OPCACHE_MEMORY=256
    restart: unless-stopped
    profiles:
      - prod
