services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
  sut:
    image: alpine:3.21
    depends_on:
      - app
    command: sh -c "apk --no-cache add curl && sleep 10 && curl --silent --fail http://app:8080/php.php | grep 'PHP 8.4'"
